rem=====================================================
rem     作    者：研发部
rem     整理时间：2008-07-11
rem     说    明：公共部分同义词
rem=====================================================

conn &SystemConn

CREATE OR REPLACE PUBLIC SYNONYM MED_ADADMINSTER_MODE_DICT FOR MEDCOMM.MED_ADADMINSTER_MODE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ADMINISTRATION_DICT FOR MEDCOMM.MED_ADMINISTRATION_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ADMINISTRATION_STAT_DICT FOR MEDCOMM.MED_ADMINISTRATION_STAT_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ADT_LOG FOR MEDCOMM.MED_ADT_LOG;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANAESTHESIA_DICT FOR MEDCOMM.MED_ANAESTHESIA_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHETIC_CLASS_DICT FOR MEDCOMM.MED_ANESTHETIC_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_APPLICATIONS FOR MEDCOMM.MED_APPLICATIONS;
CREATE OR REPLACE PUBLIC SYNONYM MED_AREA_DICT FOR MEDCOMM.MED_AREA_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_BED_REC FOR MEDCOMM.MED_BED_REC;
CREATE OR REPLACE PUBLIC SYNONYM MED_BILL_ITEM_CLASS_DICT FOR MEDCOMM.MED_BILL_ITEM_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_BILL_ITEM_CLASS_VS_HIS FOR MEDCOMM.MED_BILL_ITEM_CLASS_VS_HIS;
CREATE OR REPLACE PUBLIC SYNONYM MED_CHARGE_PRICE_SCHEDULE FOR MEDCOMM.MED_CHARGE_PRICE_SCHEDULE;
CREATE OR REPLACE PUBLIC SYNONYM MED_CHARGE_TYPE_DICT FOR MEDCOMM.MED_CHARGE_TYPE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_CLINIC_ITEM_NAME_DICT FOR MEDCOMM.MED_CLINIC_ITEM_NAME_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_CLINIC_VS_CHARGE FOR MEDCOMM.MED_CLINIC_VS_CHARGE;
CREATE OR REPLACE PUBLIC SYNONYM MED_CURRENT_PRICE_LIST FOR MEDCOMM.MED_CURRENT_PRICE_LIST;
CREATE OR REPLACE PUBLIC SYNONYM MED_DEPT_DICT FOR MEDCOMM.MED_DEPT_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DEPT_EQUIP_DICT FOR MEDCOMM.MED_DEPT_EQUIP_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DEPT_VS_WARD FOR MEDCOMM.MED_DEPT_VS_WARD;
CREATE OR REPLACE PUBLIC SYNONYM MED_DIAGNOSIS_DICT FOR MEDCOMM.MED_DIAGNOSIS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DOSAGE_UNITS_DICT FOR MEDCOMM.MED_DOSAGE_UNITS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_CLASS_DICT FOR MEDCOMM.MED_DRUG_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_DICT FOR MEDCOMM.MED_DRUG_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_FORM_DICT FOR MEDCOMM.MED_DRUG_FORM_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_NAME_DICT FOR MEDCOMM.MED_DRUG_NAME_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_RETURN_CLASS_DICT FOR MEDCOMM.MED_DRUG_RETURN_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_EXAM_ITEMS FOR MEDCOMM.MED_EXAM_ITEMS;
CREATE OR REPLACE PUBLIC SYNONYM MED_EXAM_MASTER FOR MEDCOMM.MED_EXAM_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_EXAM_NO_SEQ FOR MEDCOMM.MED_EXAM_NO_SEQ;
CREATE OR REPLACE PUBLIC SYNONYM MED_EXAM_REPORT FOR MEDCOMM.MED_EXAM_REPORT;
CREATE OR REPLACE PUBLIC SYNONYM MED_HIS_USERS FOR MEDCOMM.MED_HIS_USERS;
CREATE OR REPLACE PUBLIC SYNONYM MED_HOSPITAL_CONFIG FOR MEDCOMM.MED_HOSPITAL_CONFIG;
CREATE OR REPLACE PUBLIC SYNONYM MED_ICU_CONFIG FOR MEDCOMM.MED_ICU_CONFIG;
CREATE OR REPLACE PUBLIC SYNONYM MED_IDENTITY_DICT FOR MEDCOMM.MED_IDENTITY_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_IF_RUN_CONFIG_DICT FOR MEDCOMM.MED_IF_RUN_CONFIG_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_IF_TRANS_DICT FOR MEDCOMM.MED_IF_TRANS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_JOB_CLASS_DICT FOR MEDCOMM.MED_JOB_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_LAB_REPORT_ITEM_DICT FOR MEDCOMM.MED_LAB_REPORT_ITEM_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_LAB_RESULT FOR MEDCOMM.MED_LAB_RESULT;
CREATE OR REPLACE PUBLIC SYNONYM MED_LAB_TEST_ITEMS FOR MEDCOMM.MED_LAB_TEST_ITEMS;
CREATE OR REPLACE PUBLIC SYNONYM MED_LAB_TEST_MASTER FOR MEDCOMM.MED_LAB_TEST_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_MEASURES_DICT FOR MEDCOMM.MED_MEASURES_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MONITOR_DATA_VALUES_DICT FOR MEDCOMM.MED_MONITOR_DATA_VALUES_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MONITOR_DICT FOR MEDCOMM.MED_MONITOR_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MONITOR_FUNCTION_CODE FOR MEDCOMM.MED_MONITOR_FUNCTION_CODE;
CREATE OR REPLACE PUBLIC SYNONYM MED_ICU_SHOW_DICT FOR MEDCOMM.MED_ICU_SHOW_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ICU_SHOW_SUB_DICT FOR MEDCOMM.MED_ICU_SHOW_SUB_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ICU_VALUE_TYPE_DICT FOR MEDCOMM.MED_ICU_VALUE_TYPE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DATA_TABLE_CODE_DICT FOR MEDCOMM.MED_DATA_TABLE_CODE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MONITOR_SPECIAL_CODE FOR MEDCOMM.MED_MONITOR_SPECIAL_CODE;
CREATE OR REPLACE PUBLIC SYNONYM MED_TIME_POINT_LIST FOR MEDCOMM.MED_TIME_POINT_LIST;
CREATE OR REPLACE PUBLIC SYNONYM MED_MR_FILE_INDEX FOR MEDCOMM.MED_MR_FILE_INDEX;
CREATE OR REPLACE PUBLIC SYNONYM MED_MR_INDEX FOR MEDCOMM.MED_MR_INDEX;
CREATE OR REPLACE PUBLIC SYNONYM MED_MR_WORK_PATH FOR MEDCOMM.MED_MR_WORK_PATH;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_CLASS_DICT FOR MEDCOMM.MED_MTRL_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_DICT FOR MEDCOMM.MED_MTRL_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_EXPORT_CLASS_DICT FOR MEDCOMM.MED_MTRL_EXPORT_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_IMPORT_CLASS_DICT FOR MEDCOMM.MED_MTRL_IMPORT_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_NAME_DICT FOR MEDCOMM.MED_MTRL_NAME_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_SUPPLIER_CATALOG FOR MEDCOMM.MED_MTRL_SUPPLIER_CATALOG;
CREATE OR REPLACE PUBLIC SYNONYM MED_NURSE_TEMPLETE FOR MEDCOMM.MED_NURSE_TEMPLETE;
CREATE OR REPLACE PUBLIC SYNONYM MED_NURSING_SCHEDULE_DICT FOR MEDCOMM.MED_NURSING_SCHEDULE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_DICT FOR MEDCOMM.MED_OPERATION_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_SCALE_DICT FOR MEDCOMM.MED_OPERATION_SCALE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ORDERS FOR MEDCOMM.MED_ORDERS;
CREATE OR REPLACE PUBLIC SYNONYM MED_ORDER_ATTR_DICT FOR MEDCOMM.MED_ORDER_ATTR_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ORDER_CLASS_DICT FOR MEDCOMM.MED_ORDER_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ORDER_STATUS_DICT FOR MEDCOMM.MED_ORDER_STATUS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_OUTER_APP_USE FOR MEDCOMM.MED_OUTER_APP_USE;
CREATE OR REPLACE PUBLIC SYNONYM MED_OUTER_CODING_CONFIG FOR MEDCOMM.MED_OUTER_CODING_CONFIG;
CREATE OR REPLACE PUBLIC SYNONYM MED_OUTER_GENERATION FOR MEDCOMM.MED_OUTER_GENERATION;
CREATE OR REPLACE PUBLIC SYNONYM MED_PATIENT_FORM_DATA_DICT FOR MEDCOMM.MED_PATIENT_FORM_DATA_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_PATIENT_STATUS_CHG_DICT FOR MEDCOMM.MED_PATIENT_STATUS_CHG_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_PATS_IN_HOSPITAL FOR MEDCOMM.MED_PATS_IN_HOSPITAL;
CREATE OR REPLACE PUBLIC SYNONYM MED_PAT_MASTER_INDEX FOR MEDCOMM.MED_PAT_MASTER_INDEX;
CREATE OR REPLACE PUBLIC SYNONYM MED_PAT_MONITOR_DATA_DICT FOR MEDCOMM.MED_PAT_MONITOR_DATA_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_PAT_VISIT FOR MEDCOMM.MED_PAT_VISIT;
CREATE OR REPLACE PUBLIC SYNONYM MED_PERFORM_DEFAULT_SCHEDULE FOR MEDCOMM.MED_PERFORM_DEFAULT_SCHEDULE;
CREATE OR REPLACE PUBLIC SYNONYM MED_PERMISSIONS FOR MEDCOMM.MED_PERMISSIONS;
CREATE OR REPLACE PUBLIC SYNONYM MED_PERMISSIONS_ANES FOR MEDCOMM.MED_PERMISSIONS_ANES;
CREATE OR REPLACE PUBLIC SYNONYM MED_PRICE_ITEM_NAME_DICT FOR MEDCOMM.MED_PRICE_ITEM_NAME_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_PRICE_LIST FOR MEDCOMM.MED_PRICE_LIST;
CREATE OR REPLACE PUBLIC SYNONYM MED_ROLES FOR MEDCOMM.MED_ROLES;
CREATE OR REPLACE PUBLIC SYNONYM MED_ROLES_PERMISSIONS FOR MEDCOMM.MED_ROLES_PERMISSIONS;
CREATE OR REPLACE PUBLIC SYNONYM MED_SPECIFIC_WORD_DICT FOR MEDCOMM.MED_SPECIFIC_WORD_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_DICT FOR MEDCOMM.MED_STAFF_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_VS_GROUP FOR MEDCOMM.MED_STAFF_VS_GROUP;
CREATE OR REPLACE PUBLIC SYNONYM MED_TITLE_DICT FOR MEDCOMM.MED_TITLE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_TRANSFER FOR MEDCOMM.MED_TRANSFER;
CREATE OR REPLACE PUBLIC SYNONYM MED_USERS FOR MEDCOMM.MED_USERS;
CREATE OR REPLACE PUBLIC SYNONYM MED_USERS_APPLICATIONS FOR MEDCOMM.MED_USERS_APPLICATIONS;
CREATE OR REPLACE PUBLIC SYNONYM MED_USERS_DEPTS FOR MEDCOMM.MED_USERS_DEPTS;
CREATE OR REPLACE PUBLIC SYNONYM MED_USERS_ROLES FOR MEDCOMM.MED_USERS_ROLES;
CREATE OR REPLACE PUBLIC SYNONYM MED_VS_HIS_OPER_APPLY FOR MEDCOMM.MED_VS_HIS_OPER_APPLY;
CREATE OR REPLACE PUBLIC SYNONYM MED_VS_HIS_OPER_MASTER FOR MEDCOMM.MED_VS_HIS_OPER_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_VS_HIS_ORDERS FOR MEDCOMM.MED_VS_HIS_ORDERS;
CREATE OR REPLACE PUBLIC SYNONYM MED_VS_HIS_ORDER_CLASS FOR MEDCOMM.MED_VS_HIS_ORDER_CLASS;
CREATE OR REPLACE PUBLIC SYNONYM MED_VS_HIS_PAT FOR MEDCOMM.MED_VS_HIS_PAT;
CREATE OR REPLACE PUBLIC SYNONYM MED_VS_PACS_EXAM FOR MEDCOMM.MED_VS_PACS_EXAM;
CREATE OR REPLACE PUBLIC SYNONYM MED_WOUND_GRADE_DICT FOR MEDCOMM.MED_WOUND_GRADE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_NURSING_CLASS_DICT FOR MEDCOMM.MED_NURSING_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_OCCUPATION_DICT FOR MEDCOMM.MED_OCCUPATION_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_PATIENT_STATUS_DICT FOR MEDCOMM.MED_PATIENT_STATUS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_RELATIONSHIP_DICT FOR MEDCOMM.MED_RELATIONSHIP_DICT;
CREATE OR REPLACE PUBLIC SYNONYM med_user_permissions FOR MEDCOMM.med_user_permissions;
CREATE OR REPLACE PUBLIC SYNONYM MED_MARITAL_STATUS_DICT FOR MEDCOMM.MED_MARITAL_STATUS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_SEX_DICT FOR MEDCOMM.MED_SEX_DICT;

CREATE OR REPLACE PUBLIC SYNONYM MED_BILL_CONFIG_DICT FOR MEDCOMM.MED_BILL_CONFIG_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MR_CONTENT FOR MEDCOMM.MED_MR_CONTENT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MR_FILE FOR MEDCOMM.MED_MR_FILE;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERROOM_CUPBOARD FOR MEDCOMM.MED_OPERROOM_CUPBOARD;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPER_ROOM_USERS FOR MEDCOMM.MED_OPER_ROOM_USERS;
CREATE OR REPLACE PUBLIC SYNONYM MED_USERS_INOUTTIME FOR MEDCOMM.MED_USERS_INOUTTIME;
CREATE OR REPLACE PUBLIC SYNONYM MED_USERS_ZP FOR MEDCOMM.MED_USERS_ZP;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_ITEM_CLASS FOR MEDCOMM.MED_ANESTHESIA_ITEM_CLASS;

CREATE OR REPLACE PUBLIC SYNONYM MED_VS_HIS_OPER_BILL_CONSTS FOR MEDCOMM.MED_VS_HIS_OPER_BILL_CONSTS;
CREATE OR REPLACE PUBLIC SYNONYM MED_VS_HIS_OPER_APPLY_V2 FOR MEDCOMM.MED_VS_HIS_OPER_APPLY_V2;
CREATE OR REPLACE PUBLIC SYNONYM MED_EMR_ARCHIVE_DETIAL  for MEDCOMM.MED_EMR_ARCHIVE_DETIAL;
CREATE OR REPLACE PUBLIC SYNONYM MED_EMR_CLASS_DICT  for MEDCOMM.MED_EMR_CLASS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_EMR_USERS  for MEDCOMM.MED_EMR_USERS;
CREATE OR REPLACE PUBLIC SYNONYM MED_EMR_WORK_PATH  for MEDCOMM.MED_EMR_WORK_PATH;
CREATE OR REPLACE PUBLIC SYNONYM MED_PATIENT_ARCHIVE_INFO  for MEDCOMM.MED_PATIENT_ARCHIVE_INFO;

CREATE OR REPLACE PUBLIC SYNONYM view_operation_list for medcomm.view_operation_list;
CREATE OR REPLACE PUBLIC SYNONYM med_screen_col_list for medcomm.med_screen_col_list;
CREATE OR REPLACE PUBLIC SYNONYM MED_SCREEN_CONFIG for medcomm.MED_SCREEN_CONFIG;
CREATE OR REPLACE PUBLIC SYNONYM MED_SCREEN_TEMPLATE for medcomm.MED_SCREEN_TEMPLATE;
 
CREATE OR REPLACE PUBLIC SYNONYM MONITOR_DICT FOR MEDCOMM.MED_MONITOR_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MONITOR_FUNCTION_CODE FOR MEDCOMM.MED_MONITOR_FUNCTION_CODE;
CREATE OR REPLACE PUBLIC SYNONYM med_permission_view for medcomm.med_permission_view;
CREATE OR REPLACE PUBLIC SYNONYM MED_INPUTORDER_TEMPLETE FOR MEDCOMM.MED_INPUTORDER_TEMPLETE;

CREATE OR REPLACE PUBLIC SYNONYM MED_BLOOD_GAS_DETAIL FOR MEDCOMM.MED_BLOOD_GAS_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MED_BLOOD_GAS_DICT FOR MEDCOMM.MED_BLOOD_GAS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_BLOOD_GAS_MASTER FOR MEDCOMM.MED_BLOOD_GAS_MASTER;

