//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Wis.Anes.DataAccess.WisServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServicesSoap", Namespace="http://tempuri.org/")]
    public partial class WebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SyncInterfaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLogDateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServices() {
            this.Url = global::Wis.Anes.DataAccess.Properties.Settings.Default.Anes_DataAccess_WisServiceReference_WebServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SyncInterfaceCompletedEventHandler SyncInterfaceCompleted;
        
        /// <remarks/>
        public event GetLogDateCompletedEventHandler GetLogDateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SyncInterface", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SyncInterface(string strAppType, string strSystemClass, string strInterFaceType, ParmInputData struInputData) {
            object[] results = this.Invoke("SyncInterface", new object[] {
                        strAppType,
                        strSystemClass,
                        strInterFaceType,
                        struInputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SyncInterfaceAsync(string strAppType, string strSystemClass, string strInterFaceType, ParmInputData struInputData) {
            this.SyncInterfaceAsync(strAppType, strSystemClass, strInterFaceType, struInputData, null);
        }
        
        /// <remarks/>
        public void SyncInterfaceAsync(string strAppType, string strSystemClass, string strInterFaceType, ParmInputData struInputData, object userState) {
            if ((this.SyncInterfaceOperationCompleted == null)) {
                this.SyncInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncInterfaceOperationCompleted);
            }
            this.InvokeAsync("SyncInterface", new object[] {
                        strAppType,
                        strSystemClass,
                        strInterFaceType,
                        struInputData}, this.SyncInterfaceOperationCompleted, userState);
        }
        
        private void OnSyncInterfaceOperationCompleted(object arg) {
            if ((this.SyncInterfaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncInterfaceCompleted(this, new SyncInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLogDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLogDate(string strFormat) {
            object[] results = this.Invoke("GetLogDate", new object[] {
                        strFormat});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLogDateAsync(string strFormat) {
            this.GetLogDateAsync(strFormat, null);
        }
        
        /// <remarks/>
        public void GetLogDateAsync(string strFormat, object userState) {
            if ((this.GetLogDateOperationCompleted == null)) {
                this.GetLogDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLogDateOperationCompleted);
            }
            this.InvokeAsync("GetLogDate", new object[] {
                        strFormat}, this.GetLogDateOperationCompleted, userState);
        }
        
        private void OnGetLogDateOperationCompleted(object arg) {
            if ((this.GetLogDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLogDateCompleted(this, new GetLogDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ParmInputData {
        
        private string performedcodeField;
        
        private string patientidField;
        
        private string inpnoField;
        
        private int visitidField;
        
        private int operidField;
        
        private System.DateTime startdatetimeField;
        
        private System.DateTime stopdatetimeField;
        
        private string itemclassField;
        
        private string itemnameField;
        
        private string itemcodeField;
        
        private string itemspecField;
        
        private decimal amountField;
        
        private string unitsField;
        
        private string itemtypeField;
        
        private int itemnoField;
        
        private string orderedbyField;
        
        private string performedbyField;
        
        private decimal costsField;
        
        private decimal priceField;
        
        private string operatorField;
        
        private System.DateTime billingdateField;
        
        private string storagecodeField;
        
        private string reserved01Field;
        
        private string reserved02Field;
        
        private string reserved03Field;
        
        private string reserved04Field;
        
        private string reserved05Field;
        
        private string reserved06Field;
        
        private string reserved07Field;
        
        private string reserved08Field;
        
        private string reserved09Field;
        
        private string reserved10Field;
        
        private decimal reserved11Field;
        
        private decimal reserved12Field;
        
        private decimal reserved13Field;
        
        private System.DateTime reserved14Field;
        
        private System.DateTime reserved15Field;
        
        private System.DateTime reserved16Field;
        
        private string reserved17Field;
        
        private string reserved18Field;
        
        private string reserved19Field;
        
        private string reserved20Field;
        
        private System.Data.DataSet appDatasetField;
        
        /// <remarks/>
        public string performedcode {
            get {
                return this.performedcodeField;
            }
            set {
                this.performedcodeField = value;
            }
        }
        
        /// <remarks/>
        public string patientid {
            get {
                return this.patientidField;
            }
            set {
                this.patientidField = value;
            }
        }
        
        /// <remarks/>
        public string inpno {
            get {
                return this.inpnoField;
            }
            set {
                this.inpnoField = value;
            }
        }
        
        /// <remarks/>
        public int visitid {
            get {
                return this.visitidField;
            }
            set {
                this.visitidField = value;
            }
        }
        
        /// <remarks/>
        public int operid {
            get {
                return this.operidField;
            }
            set {
                this.operidField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime startdatetime {
            get {
                return this.startdatetimeField;
            }
            set {
                this.startdatetimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime stopdatetime {
            get {
                return this.stopdatetimeField;
            }
            set {
                this.stopdatetimeField = value;
            }
        }
        
        /// <remarks/>
        public string itemclass {
            get {
                return this.itemclassField;
            }
            set {
                this.itemclassField = value;
            }
        }
        
        /// <remarks/>
        public string itemname {
            get {
                return this.itemnameField;
            }
            set {
                this.itemnameField = value;
            }
        }
        
        /// <remarks/>
        public string itemcode {
            get {
                return this.itemcodeField;
            }
            set {
                this.itemcodeField = value;
            }
        }
        
        /// <remarks/>
        public string itemspec {
            get {
                return this.itemspecField;
            }
            set {
                this.itemspecField = value;
            }
        }
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        public string itemtype {
            get {
                return this.itemtypeField;
            }
            set {
                this.itemtypeField = value;
            }
        }
        
        /// <remarks/>
        public int itemno {
            get {
                return this.itemnoField;
            }
            set {
                this.itemnoField = value;
            }
        }
        
        /// <remarks/>
        public string orderedby {
            get {
                return this.orderedbyField;
            }
            set {
                this.orderedbyField = value;
            }
        }
        
        /// <remarks/>
        public string performedby {
            get {
                return this.performedbyField;
            }
            set {
                this.performedbyField = value;
            }
        }
        
        /// <remarks/>
        public decimal costs {
            get {
                return this.costsField;
            }
            set {
                this.costsField = value;
            }
        }
        
        /// <remarks/>
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime billingdate {
            get {
                return this.billingdateField;
            }
            set {
                this.billingdateField = value;
            }
        }
        
        /// <remarks/>
        public string storagecode {
            get {
                return this.storagecodeField;
            }
            set {
                this.storagecodeField = value;
            }
        }
        
        /// <remarks/>
        public string reserved01 {
            get {
                return this.reserved01Field;
            }
            set {
                this.reserved01Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved02 {
            get {
                return this.reserved02Field;
            }
            set {
                this.reserved02Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved03 {
            get {
                return this.reserved03Field;
            }
            set {
                this.reserved03Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved04 {
            get {
                return this.reserved04Field;
            }
            set {
                this.reserved04Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved05 {
            get {
                return this.reserved05Field;
            }
            set {
                this.reserved05Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved06 {
            get {
                return this.reserved06Field;
            }
            set {
                this.reserved06Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved07 {
            get {
                return this.reserved07Field;
            }
            set {
                this.reserved07Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved08 {
            get {
                return this.reserved08Field;
            }
            set {
                this.reserved08Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved09 {
            get {
                return this.reserved09Field;
            }
            set {
                this.reserved09Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved10 {
            get {
                return this.reserved10Field;
            }
            set {
                this.reserved10Field = value;
            }
        }
        
        /// <remarks/>
        public decimal reserved11 {
            get {
                return this.reserved11Field;
            }
            set {
                this.reserved11Field = value;
            }
        }
        
        /// <remarks/>
        public decimal reserved12 {
            get {
                return this.reserved12Field;
            }
            set {
                this.reserved12Field = value;
            }
        }
        
        /// <remarks/>
        public decimal reserved13 {
            get {
                return this.reserved13Field;
            }
            set {
                this.reserved13Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime reserved14 {
            get {
                return this.reserved14Field;
            }
            set {
                this.reserved14Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime reserved15 {
            get {
                return this.reserved15Field;
            }
            set {
                this.reserved15Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime reserved16 {
            get {
                return this.reserved16Field;
            }
            set {
                this.reserved16Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved17 {
            get {
                return this.reserved17Field;
            }
            set {
                this.reserved17Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved18 {
            get {
                return this.reserved18Field;
            }
            set {
                this.reserved18Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved19 {
            get {
                return this.reserved19Field;
            }
            set {
                this.reserved19Field = value;
            }
        }
        
        /// <remarks/>
        public string reserved20 {
            get {
                return this.reserved20Field;
            }
            set {
                this.reserved20Field = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet appDataset {
            get {
                return this.appDatasetField;
            }
            set {
                this.appDatasetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SyncInterfaceCompletedEventHandler(object sender, SyncInterfaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetLogDateCompletedEventHandler(object sender, GetLogDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLogDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLogDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591