rem=====================================================
rem     作    者：研发部
rem     整理时间：2008-07-11
rem     说    明：创建麻醉同义词
rem=====================================================

connect &SystemConn
CREATE OR REPLACE PUBLIC SYNONYM MED_ANES_RECOVERY_TEMPLATE for MEDSURGERY.MED_ANES_RECOVERY_TEMPLATE;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_INQUIRY_FJSL for MEDSURGERY.MED_ANESTHESIA_INQUIRY_FJSL;
CREATE OR REPLACE PUBLIC SYNONYM MED_TABLE_COLS_MEANINGS  for MEDSURGERY.MED_TABLE_COLS_MEANINGS;                           
CREATE OR REPLACE PUBLIC SYNONYM med_mtrl_purchase_plan  for MEDSURGERY.med_mtrl_purchase_plan; 
CREATE OR REPLACE PUBLIC SYNONYM ANES_RECORD_EXT_XAXJ FOR MEDSURGERY.ANES_RECORD_EXT_XAXJ;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_COMM_DICT FOR MEDSURGERY.MED_ANESTHESIA_COMM_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_EVENT FOR MEDSURGERY.MED_ANESTHESIA_EVENT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_EVENT_NAME FOR MEDSURGERY.MED_ANESTHESIA_EVENT_NAME;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_EVENT_OPEN FOR MEDSURGERY.MED_ANESTHESIA_EVENT_OPEN;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_EVENT_TEMPLET FOR MEDSURGERY.MED_ANESTHESIA_EVENT_TEMPLET;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_INPUT_DICT FOR MEDSURGERY.MED_ANESTHESIA_INPUT_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_INQUIRY FOR MEDSURGERY.MED_ANESTHESIA_INQUIRY;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_NURSE FOR MEDSURGERY.MED_ANESTHESIA_NURSE;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_PLAN FOR MEDSURGERY.MED_ANESTHESIA_PLAN;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_RECOVERY FOR MEDSURGERY.MED_ANESTHESIA_RECOVERY;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_SUMMARY FOR MEDSURGERY.MED_ANESTHESIA_SUMMARY;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_TEMPLET FOR MEDSURGERY.MED_ANESTHESIA_TEMPLET;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANES_AGREEMENT_TEMPLET FOR MEDSURGERY.MED_ANES_AGREEMENT_TEMPLET;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANES_BILL_TEMPLET FOR MEDSURGERY.MED_ANES_BILL_TEMPLET;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANES_DRUG_UNITS_DESC FOR MEDSURGERY.MED_ANES_DRUG_UNITS_DESC;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANES_QUERY_RESULT_TEMP FOR MEDSURGERY.MED_ANES_QUERY_RESULT_TEMP;
CREATE OR REPLACE PUBLIC SYNONYM MED_BLOOD_GAS_ANALYSIS_REC FOR MEDSURGERY.MED_BLOOD_GAS_ANALYSIS_REC;
CREATE OR REPLACE PUBLIC SYNONYM MED_BLOOD_GAS_ITEM_DICT FOR MEDSURGERY.MED_BLOOD_GAS_ITEM_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_CAMERA_DICT FOR MEDSURGERY.MED_CAMERA_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DEPT_INFO_DICT FOR MEDSURGERY.MED_DEPT_INFO_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_BORROW_DETAIL FOR MEDSURGERY.MED_DRUG_BORROW_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_BORROW_MASTER FOR MEDSURGERY.MED_DRUG_BORROW_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_KEEP FOR MEDSURGERY.MED_DRUG_KEEP;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_RETURN_DETAIL FOR MEDSURGERY.MED_DRUG_RETURN_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_RETURN_MASTER FOR MEDSURGERY.MED_DRUG_RETURN_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_USE_DETAIL FOR MEDSURGERY.MED_DRUG_USE_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_USE_MASTER FOR MEDSURGERY.MED_DRUG_USE_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_EVENT_VS_CHARGE FOR MEDSURGERY.MED_EVENT_VS_CHARGE;
CREATE OR REPLACE PUBLIC SYNONYM MED_INP_BILL_DETAIL FOR MEDSURGERY.MED_INP_BILL_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MED_INQUIRY_TEMPLET FOR MEDSURGERY.MED_INQUIRY_TEMPLET;
CREATE OR REPLACE PUBLIC SYNONYM MED_MEDAPP_VER FOR MEDSURGERY.MED_MEDAPP_VER;
CREATE OR REPLACE PUBLIC SYNONYM MED_MIXED_DRUG FOR MEDSURGERY.MED_MIXED_DRUG;
CREATE OR REPLACE PUBLIC SYNONYM MED_MONITOR_FUNCTION FOR MEDSURGERY.MED_MONITOR_FUNCTION;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_EXPORT_DETAIL FOR MEDSURGERY.MED_MTRL_EXPORT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_EXPORT_DETAIL_HIS FOR MEDSURGERY.MED_MTRL_EXPORT_DETAIL_HIS;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_EXPORT_MASTER FOR MEDSURGERY.MED_MTRL_EXPORT_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_IMPORT_DETAIL FOR MEDSURGERY.MED_MTRL_IMPORT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_IMPORT_MASTER FOR MEDSURGERY.MED_MTRL_IMPORT_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_PRICE_LIST FOR MEDSURGERY.MED_MTRL_PRICE_LIST;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_PRICE_PROFIT FOR MEDSURGERY.MED_MTRL_PRICE_PROFIT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_PROVIDE_APPLICATION FOR MEDSURGERY.MED_MTRL_PROVIDE_APPLICATION;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_PROVIDE_NOTICE FOR MEDSURGERY.MED_MTRL_PROVIDE_NOTICE;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_STOCK FOR MEDSURGERY.MED_MTRL_STOCK;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_STOCK_BALANCE FOR MEDSURGERY.MED_MTRL_STOCK_BALANCE;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_STORAGE_DEPT FOR MEDSURGERY.MED_MTRL_STORAGE_DEPT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_STORAGE_PROFILE FOR MEDSURGERY.MED_MTRL_STORAGE_PROFILE;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_SUB_STORAGE_DICT FOR MEDSURGERY.MED_MTRL_SUB_STORAGE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_USE_DETAIL FOR MEDSURGERY.MED_MTRL_USE_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_USE_MASTER FOR MEDSURGERY.MED_MTRL_USE_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATING_ROOM FOR MEDSURGERY.MED_OPERATING_ROOM;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_ANALGESIC FOR MEDSURGERY.MED_OPERATION_ANALGESIC;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_BILL_ITEMS FOR MEDSURGERY.MED_OPERATION_BILL_ITEMS;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_CANCELED FOR MEDSURGERY.MED_OPERATION_CANCELED;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_EQIP_DETAIL FOR MEDSURGERY.MED_OPERATION_EQIP_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_EQIP_TEMPLET FOR MEDSURGERY.MED_OPERATION_EQIP_TEMPLET;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_MASTER FOR MEDSURGERY.MED_OPERATION_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_NAME FOR MEDSURGERY.MED_OPERATION_NAME;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_NAME_CANCELED FOR MEDSURGERY.MED_OPERATION_NAME_CANCELED;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_NURSE_SHIFT FOR MEDSURGERY.MED_OPERATION_NURSE_SHIFT;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_SCHEDULE FOR MEDSURGERY.MED_OPERATION_SCHEDULE;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_SHIFT FOR MEDSURGERY.MED_OPERATION_SHIFT;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPER_ANALGESIC_TEMPLET FOR MEDSURGERY.MED_OPER_ANALGESIC_TEMPLET;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPER_BILL_TEMPLET FOR MEDSURGERY.MED_OPER_BILL_TEMPLET;
CREATE OR REPLACE PUBLIC SYNONYM MED_PACU_VITALSIGNS FOR MEDSURGERY.MED_PACU_VITALSIGNS;
CREATE OR REPLACE PUBLIC SYNONYM MED_PACU_VITALSIGNS_CHANGED FOR MEDSURGERY.MED_PACU_VITALSIGNS_CHANGED;
CREATE OR REPLACE PUBLIC SYNONYM MED_PAT_MONITOR_DATA FOR MEDSURGERY.MED_PAT_MONITOR_DATA;
CREATE OR REPLACE PUBLIC SYNONYM MED_PAT_MONITOR_DATA_EXT FOR MEDSURGERY.MED_PAT_MONITOR_DATA_EXT;
CREATE OR REPLACE PUBLIC SYNONYM MED_PAT_MONITOR_DATA_HISTORY FOR MEDSURGERY.MED_PAT_MONITOR_DATA_HISTORY;
CREATE OR REPLACE PUBLIC SYNONYM MED_PAT_MONITOR_PARM_DEFINE FOR MEDSURGERY.MED_PAT_MONITOR_PARM_DEFINE;
CREATE OR REPLACE PUBLIC SYNONYM MED_QUERY_COND FOR MEDSURGERY.MED_QUERY_COND;
CREATE OR REPLACE PUBLIC SYNONYM MED_QUERY_COND_SELECTION FOR MEDSURGERY.MED_QUERY_COND_SELECTION;
CREATE OR REPLACE PUBLIC SYNONYM MED_SCHEDULED_OPERATION_NAME FOR MEDSURGERY.MED_SCHEDULED_OPERATION_NAME;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_LEAVE_LOG FOR MEDSURGERY.MED_STAFF_LEAVE_LOG;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_PERSONNEL_INFO FOR MEDSURGERY.MED_STAFF_PERSONNEL_INFO;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_SCHEDULE FOR MEDSURGERY.MED_STAFF_SCHEDULE;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_SCHEDULE_DICT FOR MEDSURGERY.MED_STAFF_SCHEDULE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_SCHEDULE_REM FOR MEDSURGERY.MED_STAFF_SCHEDULE_REM;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_SCHEDULE_REM_DETAIL FOR MEDSURGERY.MED_STAFF_SCHEDULE_REM_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_TRANSFER FOR MEDSURGERY.MED_STAFF_TRANSFER;
CREATE OR REPLACE PUBLIC SYNONYM MED_ST_OPER_COSTS FOR MEDSURGERY.MED_ST_OPER_COSTS;
CREATE OR REPLACE PUBLIC SYNONYM MED_ST_OP_PER_WORKLOAD FOR MEDSURGERY.MED_ST_OP_PER_WORKLOAD;
CREATE OR REPLACE PUBLIC SYNONYM MED_ST_OP_PER_WORKLOAD_TEMP FOR MEDSURGERY.MED_ST_OP_PER_WORKLOAD_TEMP;
CREATE OR REPLACE PUBLIC SYNONYM MED_SUMMARY_TEMPLET FOR MEDSURGERY.MED_SUMMARY_TEMPLET;
CREATE OR REPLACE PUBLIC SYNONYM MED_TEMPLET_CONFIG FOR MEDSURGERY.MED_TEMPLET_CONFIG;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANES_ORDERS FOR MEDSURGERY.MED_ANES_ORDERS;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANES_ORDERS_TEMPLATE FOR MEDSURGERY.MED_ANES_ORDERS_TEMPLATE;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANES_RECORD_EXT_INFOR FOR MEDSURGERY.MED_ANES_RECORD_EXT_INFOR;
CREATE OR REPLACE PUBLIC SYNONYM MED_CALL_RECORD FOR MEDSURGERY.MED_CALL_RECORD;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_BILL FOR MEDSURGERY.MED_DRUG_BILL;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_INPUT_STORAGE FOR MEDSURGERY.MED_DRUG_INPUT_STORAGE;
CREATE OR REPLACE PUBLIC SYNONYM MED_DRUG_STORAGE FOR MEDSURGERY.MED_DRUG_STORAGE;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_INPUT_STORAGE FOR MEDSURGERY.MED_MTRL_INPUT_STORAGE;
CREATE OR REPLACE PUBLIC SYNONYM MED_MTRL_STORAGE FOR MEDSURGERY.MED_MTRL_STORAGE;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_AFTER_ORDER FOR MEDSURGERY.MED_OPERATION_AFTER_ORDER;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPER_SCHED_TEMPLATE FOR MEDSURGERY.MED_OPER_SCHED_TEMPLATE;
CREATE OR REPLACE PUBLIC SYNONYM MED_TRANSFER_SELF FOR MEDSURGERY.MED_TRANSFER_SELF;
CREATE OR REPLACE PUBLIC SYNONYM med_pat_monitor_data_temp for medsurgery.med_pat_monitor_data_temp;


CREATE OR REPLACE PUBLIC SYNONYM OPERATING_ROOM FOR MEDSURGERY.MED_OPERATING_ROOM;
CREATE OR REPLACE PUBLIC SYNONYM PATIENT_MONITOR_DATA FOR MEDSURGERY.MED_PAT_MONITOR_DATA;
CREATE OR REPLACE PUBLIC SYNONYM PATIENT_MONITOR_DATA_HISTORY FOR MEDSURGERY.MED_PAT_MONITOR_DATA_HISTORY;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_SCHEDULE_REMARK for MEDSURGERY.MED_STAFF_SCHEDULE_REMARK;
CREATE OR REPLACE PUBLIC SYNONYM MED_STAFF_SCHEDULE_REMARK_D for MEDSURGERY.MED_STAFF_SCHEDULE_REMARK_D;



rem==================================
rem      创建 为重评分相关脚本
rem==================================

CREATE OR REPLACE PUBLIC SYNONYM patient_class_dict  for MEDSURGERY.patient_class_dict;
CREATE OR REPLACE PUBLIC SYNONYM pat_adm_condition_dict  for MEDSURGERY.pat_adm_condition_dict;
CREATE OR REPLACE PUBLIC SYNONYM APACHE2_SCORING_RESULT_DETAIL  for MEDSURGERY.APACHE2_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM APGAR_SCORING_RESULT_DETAIL  for MEDSURGERY.APGAR_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM BALTH_SCORING_RESULT_DETAIL  for MEDSURGERY.BALTH_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM CG_SCORING_RESULT_DETAIL  for MEDSURGERY.CG_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM CPUGH_SCORING_RESULT_DETAIL  for MEDSURGERY.CPUGH_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM CRAMS_SCORING_RESULT_DETAIL  for MEDSURGERY.CRAMS_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM CRIB_SCORING_RESULT_DETAIL  for MEDSURGERY.CRIB_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM CSSS_SCORING_RESULT_DETAIL  for MEDSURGERY.CSSS_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM GCS_SCORING_RESULT_DETAIL  for MEDSURGERY.GCS_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM GOLDMAN_SCORING_RESULT_DETAIL  for MEDSURGERY.GOLDMAN_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM GP_SCORING_RESULT_DETAIL  for MEDSURGERY.GP_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM IMP_ITEM_VS_DICT  for MEDSURGERY.IMP_ITEM_VS_DICT;
CREATE OR REPLACE PUBLIC SYNONYM LUTZ_SCORING_RESULT_DETAIL  for MEDSURGERY.LUTZ_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MODS2_SCORING_RESULT_DETAIL  for MEDSURGERY.MODS2_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM MODS_SCORING_RESULT_DETAIL  for MEDSURGERY.MODS_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM NORTON_SCORING_RESULT_DETAIL  for MEDSURGERY.NORTON_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM PARS_SCORING_RESULT_DETAIL  for MEDSURGERY.PARS_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM PATIENT_SCORING_RESULT  for MEDSURGERY.PATIENT_SCORING_RESULT;
CREATE OR REPLACE PUBLIC SYNONYM PATIENT_SCORING_RESULT_DETAIL  for MEDSURGERY.PATIENT_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM SAPS2_SCORING_RESULT_DETAIL  for MEDSURGERY.SAPS2_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM SCORING_ITEM_LIST  for MEDSURGERY.SCORING_ITEM_LIST;
CREATE OR REPLACE PUBLIC SYNONYM TISS_SCORING_RESULT_DETAIL  for MEDSURGERY.TISS_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM SSS_SCORING_RESULT_DETAIL  for MEDSURGERY.SSS_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM SSSS_SCORING_RESULT_DETAIL  for MEDSURGERY.SSSS_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM SOFA_SCORING_RESULT_DETAIL  for MEDSURGERY.SOFA_SCORING_RESULT_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM SCORING_VALUE_MEMO_DICT  for MEDSURGERY.SCORING_VALUE_MEMO_DICT;
CREATE OR REPLACE PUBLIC SYNONYM SCORING_METHOD_DICT  for MEDSURGERY.SCORING_METHOD_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_CHECKED_NEW for MEDSURGERY.MED_OPERATION_CHECKED_NEW;



CREATE OR REPLACE PUBLIC SYNONYM MED_EQIP_CHECK_RECORD for MEDSURGERY.MED_EQIP_CHECK_RECORD;
CREATE OR REPLACE PUBLIC SYNONYM MED_OPERATION_EQIP_CHECK_DICT for MEDSURGERY.MED_OPERATION_EQIP_CHECK_DICT;
CREATE OR REPLACE PUBLIC SYNONYM EQUIP_MATERIAL for MEDSURGERY.EQUIP_MATERIAL;
CREATE OR REPLACE PUBLIC SYNONYM GUID_PARAMS for MEDSURGERY.GUID_PARAMS;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANESTHESIA_MASTER for MEDSURGERY.MED_ANESTHESIA_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_ANES_TYPE_DICT for MEDSURGERY.MED_ANES_TYPE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_CONFIG for MEDSURGERY.MED_CONFIG;
CREATE OR REPLACE PUBLIC SYNONYM MED_CUSTOMFIELD_DICT for MEDSURGERY.MED_CUSTOMFIELD_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_CUSTOM_DATA for MEDSURGERY.MED_CUSTOM_DATA;
CREATE OR REPLACE PUBLIC SYNONYM MED_CUSTOM_DATA_EXT for MEDSURGERY.MED_CUSTOM_DATA_EXT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DICT_SIMPLETYPES for MEDSURGERY.MED_DICT_SIMPLETYPES;
CREATE OR REPLACE PUBLIC SYNONYM MED_DICT_SIMPLETYPES_TREE for MEDSURGERY.MED_DICT_SIMPLETYPES_TREE;
CREATE OR REPLACE PUBLIC SYNONYM MED_DOCUMENT for MEDSURGERY.MED_DOCUMENT;
CREATE OR REPLACE PUBLIC SYNONYM MED_DOCUMENT_TEMPLET for MEDSURGERY.MED_DOCUMENT_TEMPLET;
CREATE OR REPLACE PUBLIC SYNONYM MED_MODIFY_HISTORY for MEDSURGERY.MED_MODIFY_HISTORY;
CREATE OR REPLACE PUBLIC SYNONYM MED_NORMAL_TYPE_DICT for MEDSURGERY.MED_NORMAL_TYPE_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_PATIENT_MONITOR_CONFIG for MEDSURGERY.MED_PATIENT_MONITOR_CONFIG;
CREATE OR REPLACE PUBLIC SYNONYM MED_PATIENT_MONITOR_DATA for MEDSURGERY.MED_PATIENT_MONITOR_DATA;
CREATE OR REPLACE PUBLIC SYNONYM MED_PERKIND_RELA for MEDSURGERY.MED_PERKIND_RELA;
CREATE OR REPLACE PUBLIC SYNONYM MED_PERMISSIONS_KIND for MEDSURGERY.MED_PERMISSIONS_KIND;
CREATE OR REPLACE PUBLIC SYNONYM MED_PLANDRUGS for MEDSURGERY.MED_PLANDRUGS;
CREATE OR REPLACE PUBLIC SYNONYM OPER_SAFE_CHECK for MEDSURGERY.OPER_SAFE_CHECK;
CREATE OR REPLACE PUBLIC SYNONYM PATIENT_EXTEND_INFO for MEDSURGERY.PATIENT_EXTEND_INFO;

CREATE OR REPLACE PUBLIC SYNONYM MED_CPB_BLG_RECORD for MEDSURGERY.MED_CPB_BLG_RECORD;
CREATE OR REPLACE PUBLIC SYNONYM MED_CPB_EVENT_OPEN for MEDSURGERY.MED_CPB_EVENT_OPEN;
CREATE OR REPLACE PUBLIC SYNONYM MED_CPB_EXAM_INFO for MEDSURGERY.MED_CPB_EXAM_INFO;
CREATE OR REPLACE PUBLIC SYNONYM MED_CPB_SUMMARY for MEDSURGERY.MED_CPB_SUMMARY;
CREATE OR REPLACE PUBLIC SYNONYM MED_CPB_INPUT_DICT for MEDSURGERY.MED_CPB_INPUT_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_CPB_MASTER for MEDSURGERY.MED_CPB_MASTER;
CREATE OR REPLACE PUBLIC SYNONYM MED_CPB_METHOD_DICT for MEDSURGERY.MED_CPB_METHOD_DICT;
CREATE OR REPLACE PUBLIC SYNONYM MED_CPB_PRE_CHECK_RECORD for MEDSURGERY.MED_CPB_PRE_CHECK_RECORD;
CREATE OR REPLACE PUBLIC SYNONYM MED_CPB_PRIMING_DATA  for MEDSURGERY.MED_CPB_PRIMING_DATA ;

create or replace public synonym MED_QIXIE_QINGDIAN
  for MEDSURGERY.MED_QIXIE_QINGDIAN;
create or replace public synonym MED_GRID_TEMPLET_MASTER
  for MEDSURGERY.MED_GRID_TEMPLET_MASTER;
create or replace public synonym MED_GRID_TEMPLET_DETAIL
  for MEDSURGERY.MED_GRID_TEMPLET_DETAIL;
create or replace public synonym MED_QIXIE_TEMPLET_MASTER
  for MEDSURGERY.MED_QIXIE_TEMPLET_MASTER;
create or replace public synonym MED_QIXIE_TEMPLET_DETAIL
  for MEDSURGERY.MED_QIXIE_TEMPLET_DETAIL;