
--赵志成 2011年3月4日 麻醉单药物曲线左侧默认项目配置

CREATE OR REPLACE PUBLIC synonym MED_PATIENT_DRUG_ITEM for MEDSURGERY.MED_PATIENT_DRUG_ITEM;


--创建同义词
create or replace public synonym MED_PACU_HANDOVER_PUTPIPE for MEDSURGERY.MED_PACU_HANDOVER_PUTPIPE;
--创建同义词
create or replace public synonym MED_PACU_HANDOVER_ORDERS for MEDSURGERY.MED_PACU_HANDOVER_ORDERS;
create or replace public synonym MED_PACU_SORCE for MEDSURGERY.MED_PACU_SORCE;
--创建同义词
create or replace public synonym MED_ANES_OPERHANDOVER for MEDSURGERY.MED_ANES_OPERHANDOVER;
--创建同义词
CREATE or replace PUBLIC SYNONYM MED_PUNCTURE_RECORD FOR MEDSURGERY.MED_PUNCTURE_RECORD;
-- Create public synonym
CREATE or replace PUBLIC SYNONYM MED_OPER_SHIFT_RECORD FOR MEDSURGERY.MED_OPER_SHIFT_RECORD;
