

--用MedSurgery创建视图
CREATE OR REPLACE VIEW SCHEDULEREPORTVIEW AS
SELECT A.OPERATING_ROOM_NO || '-' || A.SEQUENCE AS OPERATING_ROOM_NO_SEQUENCE,A.SCHEDULED_DATE_TIME,B.NAME AS PAT_NAME,TO_CHAR(SYSDATE,'YYYY') - TO_CHAR(B.DATE_OF_BIRTH,'YYYY') AS PAT_AGE,A.PATIENT_ID, A.BED_NO AS BED_NO,B.SEX,A.DIAG_BEFORE_OPERATION,
A.OPERATION_NAME,NVL(D.USER_NAME,A.SURGEON) AS SURGEON_NAME,NVL(TRIM(E.USER_NAME),A.FIRST_ASSISTANT) AS FIRST_ASSISTANT_NAME,NVL(TRIM(F.USER_NAME),A.SECOND_ASSISTANT) AS SECOND_ASSISTANT_NAME,NVL(TRIM(G.USER_NAME),A.THIRD_ASSISTANT) AS THIRD_ASSISTANT_NAME, NVL(TRIM(H.USER_NAME), A.FOURTH_ASSISTANT) AS FOURTH_ASSISTANT_NAME,
NVL(TRIM(O.ANAESTHESIA_SHORTEN),A.ANESTHESIA_METHOD) AS ANESTHESIA_METHOD,I.USER_NAME AS ANESTHESIA_DOCTOR_NAME,A.OPERATING_DEPT,Y.DEPT_NAME AS OPERATING_DEPT_NAME,
J.USER_NAME AS ANESTHESIA_ASSISTANT_NAME, NVL(TRIM(X.NAME_SHORTEN),W.USER_NAME) AS SECOND_ANESTHESIA_NAME,A.OPERATING_ROOM_NO,
CASE WHEN NVL(TRIM(K.USER_NAME),'-1') = '-1' THEN  NVL(TRIM(R.NAME_SHORTEN),M.USER_NAME)  ELSE CASE WHEN NVL(TRIM(M.USER_NAME),'-1') = '-1' THEN  NVL(TRIM(P.NAME_SHORTEN),K.USER_NAME) ELSE NVL(TRIM(P.NAME_SHORTEN),K.USER_NAME)|| '/' || NVL(TRIM(R.NAME_SHORTEN),M.USER_NAME) END END AS FIRST_OPERATION_NURSE_NAME,
CASE WHEN NVL(TRIM(L.USER_NAME),'-1') = '-1' THEN  NVL(TRIM(S.NAME_SHORTEN),N.USER_NAME)  ELSE CASE WHEN NVL(TRIM(N.USER_NAME),'-1') = '-1' THEN  NVL(TRIM(Q.NAME_SHORTEN),L.USER_NAME) ELSE NVL(TRIM(Q.NAME_SHORTEN),L.USER_NAME)|| '/' || NVL(TRIM(S.NAME_SHORTEN),N.USER_NAME) END END AS FIRST_SUPPLY_NURSE_NAME,
V.DEPT_NAME AS WARD_CODE_NAME,B.INP_NO
FROM MED_OPERATION_SCHEDULE A LEFT OUTER JOIN MED_PAT_MASTER_INDEX B ON A.PATIENT_ID = B.PATIENT_ID
LEFT OUTER JOIN MED_HIS_USERS D ON A.SURGEON = D.USER_ID
LEFT OUTER JOIN MED_HIS_USERS E ON A.FIRST_ASSISTANT = E.USER_ID
LEFT OUTER JOIN MED_HIS_USERS F ON A.SECOND_ASSISTANT = F.USER_ID
LEFT OUTER JOIN MED_HIS_USERS G ON A.THIRD_ASSISTANT = G.USER_ID
LEFT OUTER JOIN MED_HIS_USERS H ON A.FOURTH_ASSISTANT = H.USER_ID
LEFT OUTER JOIN MED_HIS_USERS I ON A.ANESTHESIA_DOCTOR = I.USER_ID
LEFT OUTER JOIN MED_HIS_USERS J ON A.ANESTHESIA_ASSISTANT = J.USER_ID
LEFT OUTER JOIN MED_HIS_USERS K ON A.FIRST_OPERATION_NURSE = K.USER_ID
LEFT OUTER JOIN MED_HIS_USERS L ON A.FIRST_SUPPLY_NURSE = L.USER_ID
LEFT OUTER JOIN MED_HIS_USERS M ON A.SECOND_OPERATION_NURSE = M.USER_ID
LEFT OUTER JOIN MED_HIS_USERS N ON A.SECOND_SUPPLY_NURSE = N.USER_ID
LEFT OUTER JOIN MED_ANAESTHESIA_DICT O ON A.ANESTHESIA_METHOD = O.ANAESTHESIA_NAME
LEFT OUTER JOIN MED_SYSTEM_CONFIG_USER P ON K.USER_ID = P.USER_ID
LEFT OUTER JOIN MED_SYSTEM_CONFIG_USER Q ON L.USER_ID = Q.USER_ID
LEFT OUTER JOIN MED_SYSTEM_CONFIG_USER R ON M.USER_ID = R.USER_ID
LEFT OUTER JOIN MED_SYSTEM_CONFIG_USER S ON N.USER_ID = S.USER_ID
LEFT OUTER JOIN MED_DEPT_DICT T ON A.DEPT_STAYED = T.DEPT_CODE
LEFT OUTER JOIN MED_PATS_IN_HOSPITAL U ON A.PATIENT_ID = U.PATIENT_ID AND A.VISIT_ID = U.VISIT_ID
LEFT OUTER JOIN MED_DEPT_DICT V ON U.WARD_CODE = V.DEPT_CODE
LEFT OUTER JOIN MED_HIS_USERS W ON A.SECOND_ANESTHESIA_ASSISTANT = W.USER_ID
LEFT OUTER JOIN MED_SYSTEM_CONFIG_USER X ON W.USER_ID = X.USER_ID
LEFT OUTER JOIN MED_DEPT_DICT Y ON A.OPERATING_DEPT = Y.DEPT_CODE
WHERE (A.STATE = 3 OR A.STATE = 2)
ORDER BY TO_NUMBER(REPLACE(A.OPERATING_ROOM_NO,'-','.')),A.SEQUENCE



